# -*- coding: utf-8 -*-
"""auto_portscan_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9Aw386o7AMAZFDKsGKRQO3bMKscmyTd
"""

import os
import time
import subprocess
from datetime import datetime

# 설정값
INTERVAL = 120  # 수집 주기 (초)
TARGET_IP = "172.17.0.2"  # 포트 스캔 대상 (자기 자신)
DEST_HOST = "capdes2@203.253.145.74"  # 전송 대상 호스트
DEST_PATH = "/home/capdes2/traffic_data"  # 호스트 내 저장 경로
PORT_RANGE = 1000  # 스캔할 포트 개수

print("포트스캔 트래픽 자동 생성 및 전송 시작")

while True:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    pcap_file = f"portscan_{timestamp}.pcap"

    print(f"[{timestamp}] 포트 스캔 트래픽 생성 시작")
    subprocess.Popen(
        ["hping3", "-S", TARGET_IP, "-p", f"++1", "-c", str(PORT_RANGE)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    subprocess.run(
        ["timeout", str(INTERVAL), "tcpdump", "-i", "any", "-w", pcap_file,
         "tcp[tcpflags] & tcp-syn != 0", "and", "src", "host", TARGET_IP],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    print(f"[{timestamp}] 패킷 수집 완료: {pcap_file}")

    result = subprocess.run(
        ["scp", "-P", "6304", pcap_file, f"{DEST_HOST}:{DEST_PATH}/"]
    )

    if result.returncode == 0:
        print("전송 성공 → 로컬 파일 삭제")
        os.remove(pcap_file)
    else:
        print("전송 실패 → 로컬 파일 보존됨")

    print("다음 주기까지 대기 중...\n")
    time.sleep(INTERVAL)