# -*- coding: utf-8 -*-
"""capture_traffic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9Aw386o7AMAZFDKsGKRQO3bMKscmyTd
"""

# TCP만
from scapy.all import sniff, wrpcap
import os
import time
from datetime import datetime

captured_packets=[]  # 캡처한 패킷 저장 리스트

# TCP 패킷 캡처해 리스트에 저장하는 함수
def packet_callback(packet):
    if packet.haslayer("TCP"):  # TCP 패킷만 캡처 (BPF 적용 안되는 환경에서도 처리)
        captured_packets.append(packet)  # 원본 패킷 저장
        print("TCP 패킷 캡처됨")

print("실시간 TCP 트래픽 수집 및 전송 시작 (1분 단위)")
start_time=time.time()
interval=60

try:
    while True:
        sniff(timeout=1, prn=packet_callback, filter="tcp", iface="eno1", store=False)

        current_time=time.time()
        if current_time-start_time>=interval and captured_packets:
            #타임스탬프 기반 파일명 생성
            timestamp=datetime.now().strftime("%Y%m%d_%H%M%S")
            filename=f"captured_tcp_traffic_{timestamp}.pcap"
            wrpcap(filename, captured_packets)
            print(f"저장 완료: {filename}")

            # 서버로 전송
            command=f"scp -P 6304 {filename} capdes2@203.253.145.74:/home/capdes2/traffic_data/"
            os.system(command)
            print("전송 완료")

            # 패킷 리스트 초기화 및 타이머 초기화
            captured_packets.clear()
            start_time=current_time
except KeyboardInterrupt:
    print("\n수집 중단")