# -*- coding: utf-8 -*-
"""collector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9Aw386o7AMAZFDKsGKRQO3bMKscmyTd
"""

from scapy.all import sniff, wrpcap
import time

while True:
    timestamp = time.strftime("%Y%m%d_%H%M%S")
    filename = f"/app/shared/traffic_data/captured_tcp_{timestamp}.pcap"
    packets = sniff(filter="tcp", timeout=60)
    wrpcap(filename, packets)
    print(f"[INFO] 저장 완료: {filename}")