# -*- coding: utf-8 -*-
"""watcher_script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9Aw386o7AMAZFDKsGKRQO3bMKscmyTd
"""

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# 감시할 디렉토리 설정
WATCH_DIRECTORY="/home/capdes2/traffic_data"
# 감시할 파일 확장자
FILE_EXTENSION=".pcap"
# 전처리 및 모델 입력 스크립트 경로
PREPROCESS_SCRIPT="preprocessandinput.py"

# 이벤트 핸들러 클래스 정의
class PcapHandler(FileSystemEventHandler):
    def on_created(self, event):
        # 새 파일이 생성되고 .pcap 확장자라면 (모든 이벤트 감지 방지)
        if not event.is_directory and event.src_path.endswith(FILE_EXTENSION):
            print(f"감지된 파일: {event.src_path}")

            # 전처리 코드 실행
            try:
                subprocess.run(["python3", PREPROCESS_SCRIPT, event.src_path], check=True)
                print("전처리 완료\n")
            except subprocess.CalledProcessError as e:
                print(f"전처리 실패: {e}")

# 감시 시작
if __name__=="__main__":
    print(f"디렉토리 감시 시작: {WATCH_DIRECTORY}")
    event_handler=PcapHandler()
    observer=Observer()
    observer.schedule(event_handler, path=WATCH_DIRECTORY, recursive=False)
    observer.start()
    try:
        while True:
            time.sleep(1)  # 감시 루프 유지
    except KeyboardInterrupt:
        observer.stop()
        print("\n감시 중단됨")
    observer.join()